server:
  port: 7000
spring:
  application:
    name: config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/gerry123/oarnge-config
#          username: 271314998@qq.com
#          password: Aa123456!
#          basedir: D:\develope\Idea\WorkSpace\gosun-parent\basedir
  profiles:
    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: D:/cof
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
